name: lsst_train
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.7
  - astropy>3.2.1
  - ipython=7.6.*
  - ipywidgets=7.5.*
  - jupyter
  - jupyterlab
  - notebook>6.0.0
  - numcodecs=0.6.*
  - numpy=1.16.*
  - pandas=0.24.*
  - scipy=1.3.*
  - widgetsnbextension=3.5.*
  - zarr=2.4.*
  - matplotlib>=2.2.3
  - pip:
    - ipytree==0.1.5

